services:
  apps:
    container_name: ct-simpleapps-syakur
    image: deni02/simpleapps-syakur
    build: ./apps
    ports:
      - "10014:3000"
    restart: always
    env_file: ./apps/.env
    #bejabjdbjad